### ISSUE TITLE
Banned Players that are Verified can still join the server.

### ISSUE THREAD

**Issue by Tjonna** [xImAnton/minecraft-discord-verification#11] opened 2022-01-04 22:03 UTC
Hi there, so as the title mentioned. If you're verified nothing is stopping you from joining.

Maybe also whitelist servers?

**Comment by Tjonna** [comment] 2022-01-04 22:04
I also tested it by removing the plugin, afterwards I could not enter anymore.

**Comment by xImAnton** [comment] 2022-01-07 12:41
should be fixed now

**Closed** 2022-01-07 12:43 UTC
Labels: bug

**Comment by Tjonna** [comment] 2022-01-11 11:36
> should be fixed now

Doesn't seem to work for me. Are you sure? I did a completely fresh install on a paper server.

**Comment by xImAnton** [comment] 2022-02-06 13:20
Have you used the new release? I'm very sure it should work now, couldn't reproduce this in my test environment.
